fix,build: Disable sccache
Sccache mysteriously fails on CI with
```
error: failed to execute compile
caused by: error reading compile response from server
caused by: Failed to read response header
caused by: failed to fill whole buffer
```

This commit disables sccache as a quickfix with
SCCACHE_IDLE_TIMEOUT=0 as per gecko-dev@8ae5eea75e1f/taskcluster/taskgraph/transforms/task.py:532
didn't help and I don't have time to investigate further.

(related: https://github.com/mozilla/sccache/issues/256)